sudo: false
language: python
env:
- TOXENV=py25
- TOXENV=py26
- TOXENV=py27
- TOXENV=py30
- TOXENV=py31
- TOXENV=py32
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=pypy3
install:
- pip install tox
- pip install python-coveralls
- pip install codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: sbuss
  password:
    secure: qMgDxMhW6HMH7Vtp2OBKG8ipWtoOj8kA1k3fx+g6lkFiCmBbP0lAU5dCdBLKWXMYmeF7OMoVm49TnRnyoTrMBuOi4sZDrXC3C2Lk1qqIe+r7dRBO+9P1MhLXp4Y6IDHgGEbt1tY8qlQV46eCvYzKOJgEYo0w7MHb0WTUbj0hnujfWm1f30XJm/gH+U2ELwLaNKH/CcsGH6iUTzINt6GMWgXDPewQ5vI+nYXUzZ69ZEclE5QUhpjjmoK7cm7wM2dx76HKtnJSKaZ/Mnzz+ffriipt1U+IFW+PxO+WL5pxuqe3pJ21Rn99lY3EyFCkvexumDzqQoxrIkf60ZwX78IFo6QIOS9Lqb3Mfsf6cVrQycRagVtU/v45HF2jOBkcOYYOeeNax3RfQOYEpRSNDP3RYJnYO28sKO3gfU/7zclx3vBs18tc0TfTI8p+TEWYrwD9HTdq2B692EzuOkXRnsVDoWIjDT79zmJRDpRAeMZqrqCY2JFokjQfTrQVAOpr2XH0aVDMqMsaNop2jfYUtLWB+veLFyRIf3mU0Olh3GCSeAUsKj+ynxUJ2/thFFefh0GEZJCHGC3u72e5I2Lj+FrCJ+KbDmo69GeZJXfsRuieTuXOBpeE8mrIXnOxnXK9ZT1o0fDhQ4lBMmYRSp+5/6KvQdSWXBb4sNQyjTfsyCJvjDI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: sbuss/pydockerfile
    branch: master
    condition: $TOXENV = py27
